print("-" *35)
print("Tugas 1 SISOP Kelas-B")
print("-" *35)
print("Nama: Raja Valentino Kristananda")
print("NPM : 21083010068")
print("-" *35)
print("Notes:")
print("-" *35)
print("Halo dunia!")
print("Ini adalah Script Python pertamaku di Linux!")
